#ifndef APPCONFIG_H
#define APPCONFIG_H

#include "pro_config.h"

//#define SERVER_PATH SERVICE_TRANS_PATH

//#define LOCKER_EXE LOCKER_TRANS

#define EXE_NAME EXE_FILTERUI_NAME

//#define FILTERUIEXE_DIR APP_PATH

#define LOG_FILE_NAME LOG_FILTERUI_FILE
#endif // APPCONFIG_H
